### ISSUE TITLE
[Endpoint] POST api/list

### ISSUE THREAD

**Issue by pawap90** [pawap90/uade-movie-api#14]
The endpoint will receive the list data on the body, extract the account id from the jwt and insert a new list with empty media items on the `list` collection.

Route: `api/list`
Method: POST
Body:
- name
- isPublic

Requires authorization

The account id must be retrieved from the jwt.

Also create the `list` model:
```
    - isDefault 
    - name 
    - accountId
    - isPublic
    - mediaItems: [
        {
            type
            id,
            title,
            description,
            imagePath,
            genres (string array),
            year
        }
    ]
```

**Comment by jaime-human** [comment]
empece con esto ya, tengo mis dudas pero voy avanzando un poco

**Comment by jaime-human** [comment]
paulaa, i just finished the endpoint for the post of lists. Im not really sure if i am obtaining the accountId the way you expected.
If you could check that, it would be very helpful.
Thanks!

**Comment by pawap90** [comment]
@jaime-human create a PR so I can check your changes and leave comments if needed
