### ISSUE TITLE
[Endpoint] PUT api/list/:listId

### ISSUE THREAD

**Issue by pawap90** [pawap90/uade-movie-api#15]
The endpoint will receive the list data on the body, the list id on the route params, extract the account id from the jwt and update the specified list's data.

Note: Must validate that the current user owns the specified list (one user cannot modify another user's lists).

Route: `api/list/:listId`
Method: PUT
Body:
- name
- isPublic

Requires authorization

The account id must be retrieved from the jwt.

**Comment by jaime-human** [comment]
Im on it!
