### ISSUE TITLE
[Endpoint] api/rate

### ISSUE THREAD

**Issue by pawap90** [pawap90/uade-movie-api#8]
The endpoint will receive the body, extract the account id from the jwt, and insert everything on the `rates` collection. 

Route: `api/rate`
Method: POST
Requires authorization
Body:
- MediaType (string: 'movie' or 'series')
- MediaId (Number)
- Rating (Number - 1 to 10)
- Comment (string)

The account id can be retrieved from the jwt.

Rate model:
- Account Id (ObjectId - required)
- MediaType (string - required)
- MediaId (Number  - required)
- Rating (Number  - required)
- Comment (string  - required)

**Comment by jaime-human** [comment]
Im on it, on branch `post-and-get-ratings-for-media-item`

**Comment by pawap90** [comment]
@jaime-human just one small detail: in the future, it'll be better to have one branch per issue. That way the PR review gets easier and fewer errors can slip through. Keeping track of your changes and test them would be easier for you too this way.

**Comment by jaime-human** [comment]
Sure, next time i will do it that way
