### ISSUE TITLE
[Endpoint] GET api/rate/:mediaType/:mediaId

### ISSUE THREAD

**Issue by pawap90** [pawap90/uade-movie-api#9]
The endpoint will receive the media type and id through the route params, extract the account id from the jwt, get all rates for the specified media (movie or series) and set `ratedByMe=true` on the rates that were created by the current user.

Route: `api/rate/:mediaType/:mediaId`
Method: GET
Requires authorization

The account id must be retrieved from the jwt.

**Comment by jaime-human** [comment]
Im on it, on branch `post-and-get-ratings-for-media-item`
